
package:
    name: spark
    version: 1.1.0

source:
    git_url: https://github.com/apache/spark
    git_tag: v1.1.0

build:
    number: 0

requirements:
    build:
        - python
        - apache-maven
        - scala 2.10.*

    run:
        - python
        - apache-maven
        - py4j

test:
    imports:
        - pyspark

    commands:
        - pyspark --help

about:
    home: https://spark.apache.org/
    license: Apache 2.0 license
