package:
  name: conda-build     # lower case name of package, may contain '-' but no spaces
  version: 1.0       # version of package. Should use the PEP-386 verlib conventions.

source:
  git_url: https://github.com/conda/conda-build.git

build:            # (optional)
  number: 1                       # (optional, defaults to 0)
  
#  entry_points:
#    - conda-build = conda_build.main_build:main
    
# the build and ccoruntime requirements:
requirements:     # (optional)
  build:
    - python

  run:
    - conda
    - pyyaml
    
    
about:            # (optional)
  home: https://github.com/conda/conda/

