package:
  name: mpi4py_mpich2   # lower case name of package, may contain '-' but no spaces
  version: 1.3.1        # version of package. Should use the PEP-386 verlib conventions.

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
  fn: mpi4py-1.3.1.tar.gz
  url: https://bitbucket.org/mpi4py/mpi4py/downloads/mpi4py-1.3.1.tar.gz


# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: 0                        # (optional, defaults to 0)

  
# the build and runtime requirements:
requirements:     # (optional)
  build:
    - python
    - cython
  run:
    - python

test:             # (optional)
# files which are copied from the recipe into the (temporary) test
# directory which are needed during testing
  files:
    - helloworld.py
# Python imports
  imports:
    - mpi4py
    
about:            # (optional)
  home: https://bitbucket.org/mpi4py/mpi4py/overview