package:
  name: mpi4py       # lower case name of package, may contain '-' but no spaces
  version: 1.3.1   # version of package. Should use the PEP-386 verlib conventions.

  
# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: 1                       # (optional, defaults to 0)

# Defines what features a package has
  features:
    - msmpi

  # Indicates that installing this package should enable (track) the given
  # features. A package does not need to have a feature to track it.
  track_features:
    - msmpi
  
# the build and runtime requirements:
requirements:     # (optional)
  build:
    - python
  run:
    - python
    - numpy >=1.9

  
about:            # (optional)
  home: http://mpi4py.googlecode.com/