package:
  name: pyopt     # lower case name of package, may contain '-' but no spaces
  version: 1.1.0.SNOPT    # version of package. Should use the PEP-386 verlib conventions.

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
  fn: pyopt1.1.0svn.tar
  url: https://dl.dropboxusercontent.com/u/1683635/pyopt1.1.0svn.tar
#  url: http://www.pyopt.org/_downloads/pyOpt-1.1.0.tar.gz
  patches:
   # List any patch files here
    - add_pyOpt_to_path_while_importing.patch

  
# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: 1                        # (optional, defaults to 0)

  
# the build and runtime requirements:
requirements:     # (optional)
  build:
    - python
  run:
    - python

  
about:            # (optional)
  home: http://www.pyopt.org/index.html