package:
  name: pyopt       # lower case name of package, may contain '-' but no spaces
  version: 1.2.0    # version of package. Should use the PEP-386 verlib conventions.

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
  git_url: file://C:/Users/Morten/Documents/GitHub/pyopt
  patches:
   # List any patch files here
    - add_pyOpt_to_path_while_importing.patch

  
# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: 1                        # (optional, defaults to 0)

# Defines what features a package has
  features:
    - SNOPT

  # Indicates that installing this package should enable (track) the given
  # features. A package does not need to have a feature to track it.
  track_features:
    - SNOPT

  
# the build and runtime requirements:
requirements:     # (optional)
  build:
    - python
    - mingw
  run:
    - python
    - numpy

  
about:            # (optional)
  home: http://www.pyopt.org/index.html