package:
  name: cobs
  version: !!str 1.0.0

source:
  fn: cobs-1.0.0.tar.gz
  url: https://pypi.python.org/packages/source/c/cobs/cobs-1.0.0.tar.gz
  md5: 1b7adb76d0d7e982be6a7f56e9865555
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  #preserve_egg_dir: True
  #entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - cobs = cobs:main
    #
    # Would create an entry point called cobs that calls cobs.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

test:
  # Python imports
  imports:
    - cobs.cobsr
    - cobs.cobs
    - cobs

  #commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://bitbucket.org/cmcqueen1975/cobs-python/
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
