package:
  name: pydicom     # lower case name of package, may contain '-' but no spaces
  version: 0.9.8

  
source:
  fn: pydicom-0.9.8.zip
  url: file://C:/Users/mel/Documents/GitHub/conda-recipes/pydicom/pydicom-0.9.8_py34.zip # [py34]
  url: https://pypi.python.org/packages/source/p/pydicom/pydicom-0.9.8.zip # [py27]
  md5: fda7e4df2dc6e7bb96ffc1471caecaad # [py27]

build:            # (optional)
  number: 0
  
  
# the build and runtime requirements:
requirements:     # (optional)
  build:
    - python
    - setuptools
    
  run:
    - python
    

about:            # (optional)
  home: https://code.google.com/p/pydicom/
  license: MIT