package:
  name: pyopt     # lower case name of package, may contain '-' but no spaces
  version: 1.1.0    # version of package. Should use the PEP-386 verlib conventions.

source:
# The source section specifies where the source code of the package is coming
# from, it may be coming from a source tarball like:
  #fn: pyOpt-1.1.0.tar.gz
  #url: http://www.pyopt.org/_downloads/pyOpt-1.1.0.tar.gz
  #fn: pyopt_svn.tar
  svn_url: http://svn.pyopt.org/trunk
  patches:
   # List any patch files here
    - add_pyOpt_to_path_while_importing.patch

   
# The build number should be incremented for new builds of the same version
build:            # (optional)
  number: 1                        # (optional, defaults to 0)

  
# the build and runtime requirements:
requirements:     # (optional)
  build:
    - python 
  run:
    - python
    - numpy

about:            # (optional)
  home: http://www.pyopt.org/index.html