package:
  name: pydy     # lower case name of package, may contain '-' but no spaces
  version: 0.2.1_dev     # version of package. Should use the PEP-386 verlib conventions.

source:
  git_url: https://github.com/pydy/pydy.git
  git_tag: motion-view-dev

build:            # (optional)
  number: 1                      # (optional, defaults to 0)

# the build and runtime requirements:
requirements:     # (optional)
  build:
    - python
    - setuptools
    - numpy
    - sympy
    
    
  run:
    - python
    - sympy
    - numpy
    - ipython
    


about:            # (optional)
  home: https://github.com/pydy/pydy
  license: MIT