package:
  name: pydy     # lower case name of package, may contain '-' but no spaces
  version: {{ environ['GIT_DESCRIBE_TAG'] }}

source:
  git_url: https://github.com/pydy/pydy.git

build:            # (optional)
    number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

# the build and runtime requirements:
requirements:     # (optional)
  build:
    - python
    - setuptools
    - numpy
    - sympy
    
    
  run:
    - python
    - sympy
    - numpy
    


about:            # (optional)
  home: https://github.com/pydy/pydy
  license: MIT