package:
  name: yt
  version: 3.0.1

source:
  fn: yt-3.0.1.tar.gz
  url: https://pypi.python.org/packages/source/y/yt/yt-3.0.1.tar.gz
  md5: 7983a358aab047ab582aa22bfa0de7fa

build:
  entry_points:
    - yt = yt.utilities.command_line:run_main

requirements:
  build:
    - python
    - numpy
    - cython
    - setuptools 
    - libpython # [win]
    - mingw # [win]
  run:
    - python
    - numpy
    - h5py
    - sympy
    - matplotlib
    - ipython

test:
  requires:
    - nose
  commands:
    - yt -h
  imports:
    - yt

about:
  home: http://yt-project.org/
  license: BSD
